export const LOGINDATA = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
};

export const SIGNUP_DATA = {
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
};

export const LOGOUT_DATA = {
  LOGOUT_START: 'LOGOUT_START',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
};
