export const LOGINDATA = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_START: 'LOGIN_START',
  LOGIN_STOP: 'LOGIN_STOP',
};

export const SIGNUP_DATA = {
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_STOP: 'SIGNUP_STOP',
};

export const LOGOUT_DATA = {
  LOGOUT_START: 'LOGOUT_START',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
};
