export const LoadPost = {
  LOADPOST_START: 'LOADPOST_START',
  LOADPOST_SUCCESS: 'LOADPOST_SUCCESS',
  LOADPOST_FAIL: 'LOADPOST_FAIL',
};

export const ItemPost = {
  ITEMPOST_START: 'ITEMPOST_START',
  ITEMPOST_SUCCESS: 'ITEMPOST_SUCCESS',
  ITEMPOST_FAIL: 'ITEMPOST_FAIL',
};
